feat: add first steps - install, hello world
TaricsArpi/elixir-starting-guide pull request #1
Opened 2024-01-12 07:59 UTC by TaricsArpi

- Added first steps guide for:
  - installation with asdf
  - hello world

2024-01-15 08:21 UTC, Shadowbeetle requested changes
I left some comments. The basics are good, but we'll need to work on that a bit more.

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +- If you install less-compatible versions of Erlang and Elixir you might
If you install incompatible

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +- The version of Erlang is often referred as the OTP version. The version of Elixir used must be compiled specifically for the version of Erlang in use.
The version of Erlang is often referred as the OTP version. You can go a long way with Elixir without understanding what OTP is. Just remember that Erlang/OTP is often used a bit similarly to GNU/Linux and its relation to Erlang is also similar to GNU's relation to Linux.

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +- Note the first line Erlang/OTP 26 must match the Erlang version that Elixir was compiled against. If they do not match, you may encounter issues.
It's best to use the version of Erlang Elixir was compiled against. You can use `elixir -v` to figure out which version you need, as highlighted above.

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +- Knowing you can use `elixir -v` to see both versions helps you quickly tell when you have compatible versions being used together.
This can be removed if my previous comment is applied

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +## Activating Elixir and Erlang versions
Setting versions

2024-01-15 08:21 UTC, Shadowbeetle commented on README.md
> +- Although we installed the versions we want, they aren’t yet activated. There are two ways to activate a version.
aren't yet set.

2024-01-15 08:21 UTC, Shadowbeetle commented on src/hello_world.exs
> +IO.puts("Hello World!")
Where to go from here?

2024-01-15 09:53 UTC, Shadowbeetle requested changes

2024-01-15 09:53 UTC, Shadowbeetle commented on README.md
> +`asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git`
```bash
$ asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
```

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +- Elixir runs on the Erlang VM
Comparison with JS/TS, how it compiles to bitcode

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +
What is "asdf"? Is it worth to use asdf for node as well?

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +- :warning: **Please exercise caution when selecting the version. It should be compatible with the Erlang version you have installed before!** :warning:
"This is different compared to JS"....

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +    - global
Does "nvm" has something similar for local / global version usage?

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +- The following command adds the Erlang plugin:
We don't have something like this in nvm because it only handles node, that's why we need these plugins.

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +- Let's just type in `IO.puts("Hello World!")` to the terminal:
Compare this with JSs "console.log"
IEx command is like "node"

2024-01-15 09:53 UTC, TaricsArpi commented on README.md
> +- We can execute this script like this:
Add compiled version as well

2024-01-17 08:58 UTC, Shadowbeetle requested changes

2024-01-17 08:58 UTC, Shadowbeetle commented on README.md
> +- Elixir's robust concurrency model, inspired by Erlang's actor-based system, enables seamless scalability and fault tolerance, making it particularly suitable for building reliable and high-performa
This smells like SEO :D can you give a more personal description from your point of view? Keep this on for now, and add your thoughts as well below in a separate section and we'll merge the two

2024-01-19 19:08 UTC, merged